version: 2

jobs:
  test:
    docker:
      - image: php:8
    steps:
      - run:
          name: Install packages and PHP extensions
          command: |
            apt-get update
            apt-get install -y git libzip-dev unzip
            docker-php-ext-install zip
      - run:
          name: Install composer
          command: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
      - run:
          name: Install php-cs-fixer (global)
          command: composer global require friendsofphp/php-cs-fixer --prefer-dist
      - checkout
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Check coding style by php-cs-fixer
          command: composer cs-fixer-check
      - run:
          name: PHPUnit
          command: |
            mkdir -p /tmp/coverage-html
            composer test -- --coverage-html /tmp/coverage-html
      - store_artifacts:
          path: /tmp/coverage-html

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
